#pragma warning disable CA1018 // 属性を AttributeUsageAttribute に設定します

namespace Benutomo.AutomaticNotifyPropertyChangedImpl.SourceGenerator.Embedding
{
    [StaticSource("Benutomo.Internal",
        Usings = ["using System;"],
        Directives = [
            "#pragma warning disable CS0436",
            "#nullable enable",
        ],
        Attributes = [
            @"[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]",
        ])]
    public sealed class AutoGeneratedInternalFieldAttribute : Attribute
    {
        public string PropertyName { get; }

        public AutoGeneratedInternalFieldAttribute(string propertyName)
        {
            PropertyName = propertyName;
        }
    }
}