#pragma warning disable CS0436
#nullable enable

namespace Benutomo.Internal
{
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public class AutoGeneratedInternalAccessorMethodAttribute : global::System.Attribute
    {
    }
}