#pragma warning disable CS0436
#nullable enable

namespace Benutomo.Internal
{
    internal class AutoGeneratedInternalFieldAttribute : global::System.Attribute
    {
        internal AutoGeneratedInternalFieldAttribute(string propertyName) { }
    }
}