#pragma warning disable CS0436
#nullable enable

namespace Benutomo.Internal
{
    public class AutoGeneratedInternalFieldAttribute : global::System.Attribute
    {
        public AutoGeneratedInternalFieldAttribute(string propertyName) { }
    }
}